services:
  - type: web
    name: smartfleet-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: smartfleet-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: DEFAULT_FROM
        value: noreply@smartfleet.com
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_WEBHOOK_ID
        sync: false
      - key: PAYPAL_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://adamo-smartfleet.netlify.app/

databases:
  - name: smartfleet-db
    plan: free
    databaseName: vrspfab_api
    user: smartfleet_user
