spring:
  application:
    name: vrspfab

  datasource:
    url: jdbc:mysql://localhost:3306/vrspfab_api?createDatabaseIfNotExist=true
    username: root
    password: mysql_root_pass
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2h in seconds
    refreshTokenExpiration: 604800 # 7 days in seconds

#  mail:
#    host: smtp.sendgrid.net
#    port: 587
#    username: apikey
#    password: your-sendgrid-api-key
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${DEFAULT_FROM}

stripe:
  api:
    secretKey: ${STRIPE_SECRET_KEY}
  webhook:
        secret: ${STRIPE_WEBHOOK_SECRET}

paypal:
  api:
        baseUrl: https://api-m.sandbox.paypal.com # Change to https://api-m.paypal.com for live
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_CLIENT_SECRET}
  mode: ${PAYPAL_MODE} # sandbox or live
  webhook:
    id: ${PAYPAL_WEBHOOK_ID}
    secret: ${PAYPAL_WEBHOOK_SECRET}

payment:
  provider: stripe # or paypal


logging:
  level:
    com.adamo.vrspfab: TRACE