spring:
  application:
    name: vrspfab

  datasource:
    url: jdbc:mysql://localhost:3306/vrspfab_api?createDatabaseIfNotExist=true
    username: root
    password: mysql_root_pass
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
