-- V24 Migration: Seed data generated on 2025-09-03 19:43:05

INSERT INTO vehicle_brands (name, description, is_active, country_of_origin, logo_url) VALUES
('Toyota', 'A global leader in automotive manufacturing, known for its reliability and innovation.', 1, 'Japan', 'https://car-brand-names.com/wp-content/uploads/2015/07/Toyota-Logo-1.png'),
('Volkswagen', 'The largest carmaker in Europe and a global leader, part of the Volkswagen Group.', 1, 'Germany', 'https://car-brand-names.com/wp-content/uploads/2016/01/Volkswagen-logo-1.png'),
('BMW', 'A luxury vehicle manufacturer renowned for precision engineering and its "Ultimate Driving Machine" slogan.', 1, 'Germany', 'https://logos-world.net/wp-content/uploads/2020/04/BMW-Logo.png'),
('Ford', 'A foundational American automaker and a global giant, famous for its Blue Oval logo.', 1, 'United States', 'https://listcarbrands.com/wp-content/uploads/2016/03/Ford-Logo.png'),
('Honda', 'A Japanese multinational known for its diverse range of products, from automobiles to motorcycles.', 1, 'Japan', 'https://logos-world.net/wp-content/uploads/2021/03/Honda-Logo.png'),
('Hyundai', 'A major South Korean automotive manufacturer, known for its value and global reach.', 1, 'South Korea', 'https://logos-world.net/wp-content/uploads/2021/03/Hyundai-Symbol.png'),
('Mercedes-Benz', 'A prestigious German brand, a symbol of luxury, performance, and the three-pointed star.', 1, 'Germany', 'https://www.car-brand-names.com/wp-content/uploads/2015/05/Mercedes-Benz-logo-2.jpg'),
('Porsche', 'A German sports car manufacturer, part of the Volkswagen Group and known for its iconic crest.', 1, 'Germany', 'https://logos-world.net/wp-content/uploads/2021/06/Porsche-Logo.png'),
('Nissan', 'A Japanese automaker with a rich history, symbolizing the "birth of the sun."', 1, 'Japan', 'https://www.car-brand-names.com/wp-content/uploads/2015/08/Nissan-logo-5.jpg'),
('Kia', 'A South Korean vehicle manufacturer and a subsidiary of the Hyundai Motor Company.', 1, 'South Korea', 'https://logos-world.net/wp-content/uploads/2021/03/Kia-Motors-Logo-1994-2012.png'),
('Audi', 'A German luxury brand and a subsidiary of the Volkswagen Group, symbolized by four interlocking rings.', 1, 'Germany', 'https://logos-world.net/wp-content/uploads/2021/03/Audi-Symbol.png'),
('Tata Motors', 'A major Indian automotive manufacturer, known for its indigenous car models.', 1, 'India', 'https://listcarbrands.com/wp-content/uploads/2017/10/2017-logo-Tata-Motors.jpg'),
('Tesla', 'An American automotive and clean energy company, specializing in electric vehicles.', 1, 'United States', 'https://logos-world.net/wp-content/uploads/2020/10/Tesla-Emblem.png');

INSERT INTO vehicle_models (name, brand_id, description, is_active) VALUES
('Corolla', 1, 'A compact sedan, one of the best-selling cars worldwide.', 1),
('Camry', 1, 'A midsize sedan known for comfort and reliability.', 1),
('RAV4', 1, 'A popular compact crossover SUV.', 1),
('Hilux', 1, 'A durable and versatile pickup truck.', 1),
('Land Cruiser', 1, 'A legendary off-road SUV with luxury features.', 1),
('Golf', 2, 'A compact hatchback, iconic in Europe.', 1),
('Passat', 2, 'A midsize family sedan and wagon.', 1),
('Tiguan', 2, 'A compact SUV with modern styling.', 1),
('Polo', 2, 'A small city-friendly hatchback.', 1),
('Touareg', 2, 'A premium midsize SUV.', 1),
('3 Series', 3, 'A luxury compact sedan with sporty handling.', 1),
('5 Series', 3, 'A midsize luxury sedan with advanced tech.', 1),
('X5', 3, 'A luxury midsize SUV.', 1),
('i8', 3, 'A plug-in hybrid sports car.', 1),
('7 Series', 3, 'A flagship full-size luxury sedan.', 1),
('F-150', 4, 'The best-selling pickup truck in the U.S.', 1),
('Mustang', 4, 'An iconic American muscle car.', 1),
('Explorer', 4, 'A popular midsize SUV.', 1),
('Escape', 4, 'A compact crossover SUV.', 1),
('Focus', 4, 'A compact sedan/hatchback.', 1),
('Civic', 5, 'A compact sedan/hatchback, very popular worldwide.', 1),
('Accord', 5, 'A midsize sedan known for reliability.', 1),
('CR-V', 5, 'A compact SUV with strong global sales.', 1),
('Pilot', 5, 'A midsize SUV.', 1),
('Fit', 5, 'A subcompact hatchback, also called Jazz in some markets.', 1),
('Elantra', 6, 'A compact sedan with modern design.', 1),
('Sonata', 6, 'A midsize sedan.', 1),
('Tucson', 6, 'A compact SUV.', 1),
('Santa Fe', 6, 'A midsize SUV.', 1),
('Kona', 6, 'A small urban crossover SUV.', 1),
('C-Class', 7, 'A compact luxury sedan.', 1),
('E-Class', 7, 'A midsize luxury sedan.', 1),
('S-Class', 7, 'A flagship full-size luxury sedan.', 1),
('GLC', 7, 'A compact luxury SUV.', 1),
('G-Class', 7, 'An iconic luxury off-road SUV.', 1),
('911', 8, 'A legendary sports car.', 1),
('Cayenne', 8, 'A luxury midsize SUV.', 1),
('Macan', 8, 'A compact luxury SUV.', 1),
('Panamera', 8, 'A luxury four-door sports sedan.', 1),
('Taycan', 8, 'An all-electric luxury sports car.', 1),
('Altima', 9, 'A midsize sedan.', 1),
('Sentra', 9, 'A compact sedan.', 1),
('Rogue', 9, 'A compact SUV.', 1),
('Leaf', 9, 'One of the first mass-market electric cars.', 1),
('GT-R', 9, 'A high-performance sports car.', 1),
('Sportage', 10, 'A compact SUV.', 1),
('Sorento', 10, 'A midsize SUV.', 1),
('Rio', 10, 'A subcompact car.', 1),
('Stinger', 10, 'A sporty fastback sedan.', 1),
('Seltos', 10, 'A subcompact SUV.', 1),
('A3', 11, 'A compact luxury sedan.', 1),
('A4', 11, 'A popular midsize luxury sedan.', 1),
('Q5', 11, 'A compact luxury SUV.', 1),
('Q7', 11, 'A midsize luxury SUV.', 1),
('R8', 11, 'A high-performance sports car.', 1),
('Nexon', 12, 'A compact SUV.', 1),
('Harrier', 12, 'A midsize SUV.', 1),
('Tiago', 12, 'A small hatchback.', 1),
('Safari', 12, 'A family SUV.', 1),
('Altroz', 12, 'A premium hatchback.', 1),
('Model S', 13, 'A luxury electric sedan.', 1),
('Model 3', 13, 'A compact electric sedan.', 1),
('Model X', 13, 'An electric SUV with falcon-wing doors.', 1),
('Model Y', 13, 'A compact electric SUV.', 1),
('Cybertruck', 13, 'An all-electric pickup truck.', 1);

INSERT INTO vehicle_categories (name, description, is_active, icon_url) VALUES
('Hatchbackk', 'Small car with an upward-swinging rear door.', 1, 'https://api.iconify.design/mdi/car-hatchback.svg'),
('SUV', 'Sport Utility Vehicle with higher ground clearance.', 1, 'https://api.iconify.design/mdi/car-suv.svg'),
('Crossover', 'Car-based SUV blending comfort and utility.', 1, 'https://api.iconify.design/mdi/car-outline.svg'),
('Pickup Truck', 'Light-duty truck with open cargo bed.', 1, 'https://api.iconify.design/mdi/car-pickup.svg'),
('Coupe', 'Sporty two-door car.', 1, 'https://api.iconify.design/mdi/car-sports.svg'),
('Convertible', 'Car with a retractable roof.', 1, 'https://api.iconify.design/mdi/car-convertible.svg'),
('Luxury Car', 'Premium features and comfort.', 1, 'https://api.iconify.design/mdi/crown-outline.svg'),
('Sports Car', 'Built for speed and handling.', 1, 'https://api.iconify.design/mdi/flag-checkered.svg'),
('Supercar', 'Ultra high-performance sports car.', 1, 'https://api.iconify.design/mdi/speedometer.svg'),
('Hypercar', 'Top-tier, cutting-edge performance car.', 1, 'https://api.iconify.design/mdi/rocket-outline.svg'),
('Electric Car', 'Powered entirely by batteries.', 1, 'https://api.iconify.design/mdi/car-electric.svg'),
('Hybrid', 'Combines engine and electric motor.', 1, 'https://api.iconify.design/mdi/leaf.svg'),
('Van', 'Utility van for cargo or tools.', 1, 'https://api.iconify.design/mdi/van-utility.svg'),
('Minivan', 'Passenger-focused family van.', 1, 'https://api.iconify.design/mdi/bus-side.svg'),
('Wagon', 'Extended cargo area under one roofline.', 1, 'https://api.iconify.design/mdi/car-estate.svg'),
('Off-Road', 'Designed for rough terrain.', 1, 'https://api.iconify.design/mdi/car-traction-control.svg'),
('Compact', 'Small, city-friendly car.', 1, 'https://api.iconify.design/mdi/car.svg'),
('Full-Size', 'Large passenger car.', 1, 'https://api.iconify.design/mdi/car-side.svg'),
('Crossover SUV', 'Smaller SUV with car-like handling.', 1, 'https://api.iconify.design/mdi/car-suv.svg'),
('Roadster', 'Lightweight two-seater open-top.', 1, 'https://api.iconify.design/mdi/car-convertible.svg'),
('Muscle Car', 'Powerful, torque-heavy performance car.', 1, 'https://api.iconify.design/mdi/engine.svg'),
('Luxury SUV', 'High-end SUV with premium features.', 1, 'https://api/iconify.design/mdi/crown-outline.svg'),
('Super SUV', 'Extreme-performance SUV.', 1, 'https://api.iconify.design/mdi/speedometer.svg');
