package com.adamo.vrspfab.notifications;

public enum NotificationType {
    BOOKING_CONFIRMATION,
    BOOKING_CANCELLATION,
    REFUND_ISSUED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    SLOT_AVAILABLE,
    SLOT_UNAVAILABLE,
    GENERAL_UPDATE,
    PROMOTION_OFFER,
    SYSTEM_ALERT,
    USER_MESSAGE,
    FEEDBACK_REQUEST,
    ACCOUNT_VERIFICATION,
    PASSWORD_RESET,
    SECURITY_ALERT,
    NEWSLETTER,
    EVENT_REMINDER,
    SURVEY_INVITATION,
    FEATURE_UPDATE,
    MAINTENANCE_NOTIFICATION,
}
